# Dockerfile for BullMQ Worker
FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl

# Dependencies
COPY package.json ./
COPY prisma ./prisma/
RUN npm install
RUN npx prisma generate

COPY tsconfig.json ./
COPY src ./src

ENV NODE_ENV=production

CMD ["npx", "tsx", "src/worker/message-worker.ts"]
